import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Buttons from "./components/Buttons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Multi Step Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-[100vh] grid place-items-center w-full px-4 py-8 bg-[#EEF5FF]">
          <div className="grid gap-6 p-4 rounded-lg overflow-hidden shadow-lg grid-cols-form bg-[#FAFBFF] w-full max-w-[1000px] h-[90%] max-h-[700px]">
            <Sidebar />
            <div className="flex flex-col gap-8 px-8 pt-16 pb-8 overflow-hidden  w-full max-w-[1000px] h-[100%] max-h-[700px]">
              {children}
              <Buttons />
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
